version: "3.8"

include:
  - path: proxy.yaml

name: shvirtd-project

services:

  db:
    image: mysql:8
    container_name: mysql-db-compose
    restart: always
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    image: cr.yandex/crpuuqe9lctl6slrhobe/netology:1.0.0
    container_name: web-app-compose
    restart: on-failure

    expose:
      - 5000

    environment:
      DB_HOST: 172.20.0.10
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      LOG_TABLE_NAME: api_logs_v2

    depends_on:
      db:
        condition: service_healthy
    networks:
      backend:
        ipv4_address: 172.20.0.5

volumes:
  db_data: {}